# Copyright (c) Datalayer, Inc. https://datalayer.io
# Distributed under the terms of the MIT License.

name: datalayer
channels:
  - conda-forge
dependencies:
  - jq
  - nodejs=18.16.1
  - pip
  - python=3.11
  - yarn=3.5.0
  - pip:
    - build
    - hatch
    - jupyter-packaging
    - jupyterlab==4.0.0
