name: jupyter-react
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter-packaging
  - matplotlib
  - nodejs=14.15.1
  - pandas
  - pip
  - pycurl
  - pytest
  - python=3.9
  - twine
  - yarn=1.22.5
  - pip:
    - jupyterlab==3.1.0
    - jupyter-server==1.13.4
    - ipywidgets==8.0.0b1
    - jupyterlab-lsp
    - python-language-server[all]
