name: jupyter-react
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter-packaging
  - matplotlib
  - nodejs=14.15.1
  - pandas
  - pip
  - pycurl
  - pytest
  - python=3.10.4
  - twine
  - yarn=1.22.19
  - pip:
    - jupyterlab==4.0.0a26
    - ipywidgets==8.0.0b1
#    - jupyterlab-lsp
#    - python-language-server[all]
    - plotly
    - bqplot
    - pyecharts
