# Copyright (c) 2021-2023 Datalayer, Inc.
#
# MIT License

[build-system]
requires = ["jupyter_packaging==0.7.9", "jupyterlab==4.1.0b0", "setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"
